version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - webscrapping
    volumes:
      - ./data:/data/db
  mvc:
    build: ./
    ports: 
      - "3000:3000"
    networks:
      - webscrapping
    depends_on:
      - mongodb
    volumes:
      - ./:/mvc

networks:
  webscrapping: